export const CATEGORIES = [
  "All",
  "Beginner",
  "Web Dev",
  "Problem Solving",
  "Data Science",
];

export const COURSES = [
  {
    id: 1,
    title: "C++ Basics",
    description:
      "Learn the fundamentals of programming with C++. Master syntax, pointers, and memory management in this comprehensive starter course designed to build a strong foundation for computer science.",
    category: "Beginner",
    level: "Beginner",
    image: "/card01.jpg",
    link: "cpp",
    color: "#3b82f6",
    duration: "8 Weeks",
    lessons: 24,
    rating: 4.8,
  },
  {
    id: 2,
    title: "Core Java",
    description:
      "Master object-oriented programming with Java. Build robust applications and understand the JVM architecture deep dive. Perfect for building enterprise-level applications.",
    category: "Problem Solving",
    level: "Beginner",
    image: "/card02.jpg",
    link: "corejava",
    color: "#ef4444",
    duration: "10 Weeks",
    lessons: 32,
    rating: 4.9,
  },
  {
    id: 3,
    title: "Python Basics",
    description:
      "Master the fundamentals of programming with Python. From scripts to web apps, unlock the power of the most versatile language used in Data Science, Web Dev, and Automation.",
    category: "Beginner",
    level: "Beginner",
    image: "/card03.png",
    link: "pythonbasics",
    color: "#eab308",
    duration: "6 Weeks",
    lessons: 18,
    rating: 4.7,
  },
  {
    id: 4,
    title: "Advanced React Patterns",
    description:
      "Level up your web development skills with advanced React concepts, hooks, state management, and performance optimization. Build scalable front-end architectures.",
    category: "Web Dev",
    level: "Advanced",
    image: "/card06.jpg",
    link: "mernstack",
    color: "#06b6d4",
    duration: "12 Weeks",
    lessons: 45,
    rating: 5.0,
  },
  {
    id: 5,
    title: "Data Structures & Algo",
    description:
      "The ultimate guide to acing technical interviews. Learn Arrays, Linked Lists, Trees, Graphs and Dynamic Programming with real-world problem-solving examples.",
    category: "Problem Solving",
    level: "Intermediate",
    image: "/card09.jpg",
    link: "dsafoundations",
    color: "#8b5cf6",
    duration: "16 Weeks",
    lessons: 60,
    rating: 4.9,
  },
  {
    id: 6,
    title: "Machine Learning 101",
    description:
      "An introduction to the world of AI. Understand regression, classification, and neural networks with hands-on projects using Python, TensorFlow and Scikit-learn.",
    category: "Data Science",
    level: "Intermediate",
    image: "/card08.jpg",
    link: "dbms",
    color: "#10b981",
    duration: "14 Weeks",
    lessons: 50,
    rating: 4.8,
  },
];
